NETWORK_PASSPHRASE = "Public Global Stellar Network; September 2025"

[[CURRENCIES]]
code = "DOPE"
issuer = "GDRXPV2DIWVGNYI7JYLMMDQU3USBETYQN6HSIBGP762LK5XFOUEK2IGV"
name = "DOPE Coin"
desc = "Utility token for the DOPE Chain app."
image = "https://mine.dopp.eu.org/assets/dope.png"
fixed_number = 100_000_000
is_asset_anchored = false
conditions = "Fixed supply; no further issuance planned."