NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

# Account Information
ACCOUNTS = [
    "GDRXPV2DIWVGNYI7JYLMMDQU3USBETYQN6HSIBGP762LK5XFOUEK2IGV"
]

# Asset Information
[[CURRENCIES]]
code = "DOPE"
issuer = "GDRXPV2DIWVGNYI7JYLMMDQU3USBETYQN6HSIBGP762LK5XFOUEK2IGV"
display_decimals = 7
name = "DOPE Coin"
desc = "DOPE Coin is the native token of the DOPE Social network."
conditions = "Fixed supply; no further issuance planned."
image = "https://mine.dopp.eu.org/assets/dope-coin.png"
max_number = 100000000000 # 100 Billion DOPE
is_unlimited = false
status = "test"

[[CURRENCIES]]
code = "GAS"
issuer = "GDRXPV2DIWVGNYI7JYLMMDQU3USBETYQN6HSIBGP762LK5XFOUEK2IGV"
display_decimals = 7
name = "GAS Token"
desc = "GAS Token is the fuel for the DOPE Social network."
conditions = "Fixed supply; no further issuance planned."
image = "https://mine.dopp.eu.org/assets/dope-coin.png"
fixed_number = 1000000 # 1 Million GAS
max_number = 1000000
is_unlimited = false
status = "test"

# Organization Information
[DOCUMENTATION]
ORG_NAME = "DOPE Social, Inc"
ORG_DBA = "DOPE Social"
ORG_URL = "https://dopp.eu.org"
ORG_LOGO = "https://mine.dopp.eu.org/assets/dope.png"
ORG_DESCRIPTION = "DOPE Social is a decentralized social network built on the Stellar blockchain."
ORG_PHYSICAL_ADDRESS = "Sampaguita, General Tinio, Nueva Ecija, Philippines"
ORG_KEYBASE = "dopesocial"
ORG_TWITTER = "dopesocial"
ORG_GITHUB = "dopesocial"

# Principals (Key personnel)
[[PRINCIPALS]]
name = "Rex Luciano"
email = "rexluciano@dopp.eu.org"
keybase = "rexluciano"
twitter = "rexluciano_offc"
github = "rexfernandezluciano"