NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[[CURRENCIES]]
code="DOPE"
issuer="GDRXPV2DIWVGNYI7JYLMMDQU3USBETYQN6HSIBGP762LK5XFOUEK2IGV"
name="Dope Token"
desc="Utility token for the Dope app."
image="https://dope.example/assets/dope.png"
fixed_number=100000000
is_asset_anchored=false
conditions="Fixed supply; no further issuance planned."